# Generated by Django 5.1.2 on 2025-01-16 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilots_count', models.IntegerField()),
                ('pilots_value', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Autodromo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_autodromo', models.CharField(max_length=150)),
                ('ano_de_criacao_autodromo', models.IntegerField(blank=True, null=True)),
                ('description_autodromo', models.TextField(blank=True, null=True)),
                ('recorde_tempo', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, upload_to='image/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autodromos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('namet', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, upload_to='logo_team/')),
                ('legendteam', models.BooleanField(default=False, null=True)),
                ('description_team', models.TextField(blank=True, null=True)),
                ('ano_de_criacao_team', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('pilot_age', models.IntegerField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='pilots/')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('market_value', models.FloatField(blank=True, null=True)),
                ('legend', models.BooleanField(default=False, null=True)),
                ('situation', models.CharField(blank=True, max_length=50, null=True)),
                ('data_de_nascimento', models.DateField(blank=True, default='1800-01-01')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pilots', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilots_team', to='pilots.team')),
            ],
        ),
    ]
