# Generated by Django 5.1 on 2024-09-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pilots',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('age', models.DateTimeField()),
                ('team', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
