# Generated by Django 5.1 on 2024-09-02 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0003_rename_pilots_pilot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('namet', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='pilot',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilots_team', to='pilots.team'),
        ),
    ]
