# Generated by Django 5.1 on 2024-09-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0004_team_alter_pilot_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='pilots/'),
        ),
    ]
