# Generated by Django 5.1.2 on 2024-12-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0005_pilot_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
