# Generated by Django 5.1.2 on 2024-12-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0006_pilot_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilots_count', models.IntegerField()),
                ('pilots_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
