# Generated by Django 5.1.2 on 2025-01-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0008_pilot_market_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilotinventory',
            name='pilots_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
