# Generated by Django 5.1.2 on 2025-01-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0009_alter_pilotinventory_pilots_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='legend',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
