# Generated by Django 5.1.2 on 2025-01-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0010_pilot_legend'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logo_team/'),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='legend',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
