# Generated by Django 5.1.2 on 2025-01-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0011_team_logo_alter_pilot_legend'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='legendteam',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
