# Generated by Django 5.1.2 on 2025-01-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0012_team_legendteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='situation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='description_team',
            field=models.TextField(blank=True, null=True),
        ),
    ]
