# Generated by Django 5.1.2 on 2025-01-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0013_pilot_situation_team_description_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='data_de_nascimento',
            field=models.DateField(blank=True, default='1800-01-01'),
        ),
        migrations.AddField(
            model_name='team',
            name='data_de_criacao',
            field=models.DateField(blank=True, default='1800-01-01'),
        ),
    ]
