# Generated by Django 5.1.2 on 2025-01-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0014_pilot_data_de_nascimento_team_data_de_criacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autodromo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_autodromo', models.CharField(max_length=150)),
                ('data_de_criacao_autodromo', models.DateField(blank=True, default='1800-01-01')),
                ('description_autodromo', models.TextField(blank=True, null=True)),
                ('recorde_tempo', models.CharField(max_length=150)),
            ],
        ),
    ]
