# Generated by Django 5.1.2 on 2025-01-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0015_autodromo'),
    ]

    operations = [
        migrations.AddField(
            model_name='autodromo',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
