# Generated by Django 5.1.2 on 2025-01-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0019_alter_pilot_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='ano_de_criacao_team',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
