# Generated by Django 5.1.2 on 2025-01-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0020_alter_team_ano_de_criacao_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autodromo',
            name='ano_de_criacao_autodromo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
