# Generated by Django 5.1.2 on 2025-01-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0021_alter_autodromo_ano_de_criacao_autodromo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='age',
            field=models.FloatField(),
        ),
    ]
