# Generated by Django 5.1.2 on 2025-01-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0022_alter_pilot_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='age',
            field=models.IntegerField(),
        ),
    ]
